### ISSUE TITLE
Automation delay

### ISSUE THREAD

**Issue by rudolfmu** [maforn/TimedShutdownAndroid#19]
The automation activity has a 2sec delay which is also announced. During these 2 sec a user can erratically tap the screen and the shutdown is stopped.
I suggested the automation so the phone could be remotely shut down. With these 2 sec a person who has (stolen) the phone  can stop this by the natural reaction of tapping the screen. If I automate and need those 2 sec I can do the delay it in my routines. If you provide the delay I can't be sure to have stopped the phone from being used.
Thank you for providing your app to us!

**Comment by maforn** [comment]
Hello rudolfmu, I understand your problem, the 2 seconds time was actually made exactly for this: giving the user enough time to react in case it was needed. I may consider adding a button to select how much time should pass between the clicks instead of setting it to 2 seconds. A little bit of time is needed by the phone to execute the action, so it cannot be set to 0 directly.

**Comment by maforn** [comment]
I've implemented what you requested. If you are not satisfied you may write me here and I'll reopen the issue.
