### ISSUE TITLE
Add option to automatically schedule a shutdown at a set time

### ISSUE THREAD

**Issue by TrickyRicky26** [maforn/TimedShutdownAndroid#2]
Hi,

first of all thanks for developing this app, it works very well!
I would like the option to have my phone turn off at a scheduled time every day. For this it might be necessary to have the app automatically start a background service for this, as ideally the timer would be set and execute even if the app is never manually opened.

But it would also be an improvement if the app could remember the last scheduled time, and offer a one-click button to set and start a timer for this same time.

Cheers ^^

**Comment by maforn** [comment]
Hello TrickyRicky,
It is quite the nice option you asked to implement, but it's also a big one (compared to the app size at the moment). Your first request, if done well, would require adding more permissions as well as redesigning the UI, which would take me quite some time. I know the UI atm is ugly, but it's just a minor pet project and I don't want to spend too much time trying to make it pretty. Another considerable problem is battery optimization, it often kills apps running in the background and if it is not handled properly it will even throw ANRs (I already had to update the app once because of that).
Your second suggestion of the last scheduled time looks far easier, and it would take me nothing to add a sharedpreference and a button for that.
If you are okay with it, I'll implement the second option, but feel free to redesign the UI or add the necessary permission if you want and make a pull request.
On a side note, I'm glad you liked and used the app, I just made it for my personal use but it's nice to know that it was useful to other people as well :)
Keep me posted about your decision.

Cheers to you as well ^-^

**Comment by TrickyRicky26** [comment]
Unfortunately I don't have the time or experience to work on this myself, so I will be happy if the suggestion with the most recent time gets added :>

**Comment by maforn** [comment]
I have just pushed the new version. As soon as google reviews my update it will be published on the Play Store as well.
Keep me updated if it does or doesn't work as requested.

**Comment by maforn** [comment]
Hi @TrickyRicky26, just wanted to say that I had more time and added all that you requested in the last update 🙂
